name: mobileapp_pinisi_ampuh_new

packages:
  - lib
  - generator/assets
  - generator/language

ide:
  intellij:
    enabled: true

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze .