name: mobileapp_pinisi_ampuh_new
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0

  # generator
  args: ^2.5.0
  dart_style: ^2.3.6
  path: ^1.9.0
  yaml: ^3.1.2
  recase: ^4.1.0
  build: ^2.4.1
  build_config: ^1.1.1

  # core/manifest
  intl: ^0.19.0
  lottie: ^3.1.2


  # core/utilities
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  collection: ^1.18.0

  equatable: ^2.0.5
  
  dartz: ^0.10.1

  injectable: ^2.4.4

  freezed_annotation: ^2.4.4

  cached_network_image: ^3.3.1

  carousel_slider: ^5.0.0

  path_provider: ^2.1.4

  permission_handler: ^11.3.1

  geolocator: ^13.0.1

  geocoding: ^3.0.0

  url_launcher: ^6.3.0

  image_picker: ^1.1.2
  adaptive_theme: ^3.6.0
  sizer: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  melos: ^6.1.0
  build_runner: ^2.4.12
  injectable_generator: ^2.6.2
  freezed: ^2.5.7
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    # Environtment
    - .env.development
    - .env.trial
    - .env.production
